apiVersion: v1
kind: Pod
metadata:
  name: mysql-volume
  labels:
    app: mysql-volume
spec:
  containers:
  - name: mysql-volume
    image: mysql
    env:
    - name: MYSQL_DATABASE
      value: eazytraining
    - name: MYSQL_ROOT_PASSWORD
      value: password
    - name: MYSQL_USER
      value: eazy
    - name: MYSQL_PASSWORD
      value: eazy
    volumeMounts:
    - name: mysqldata
      mountPath: /var/lib/mysql
  volumes:
  - name: mysqldata
    hostPath:
      path: /data-volume
