apiVersion: v1
kind: Pod
metadata:
  name: mysql-pv
  labels:
    app: mysql-pv
spec:
  containers:
  - name: mysql-pv
    image: mysql
    env:
    - name: MYSQL_DATABASE
      value: eazytraining
    - name: MYSQL_ROOT_PASSWORD
      value: password
    - name: MYSQL_USER
      value: eazy
    - name: MYSQL_PASSWORD
      value: eazy
    volumeMounts:
    - name: mysqldatapv
      mountPath: /var/lib/mysql
  volumes:
  - name: mysqldatapv
    persistentVolumeClaim:
      claimName: test-pvc
