apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-01
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: manual
  hostPath:
    path: "/data-pv"
